feat(config_error): updated error type for config module
pactus-project/pactus pull request #1153
Opened 2024-03-08 13:35 UTC by nagarajmanjunath

## Description

Briefly describe the changes introduced by this pull request.

## Related issue(s)
- Updated error type in config module.

2024-03-08 15:21 UTC, b00f requested changes

2024-03-08 15:21 UTC, b00f commented on config/config.go
> -	bootstrapInfosBytes []byte
Why did you remove this?

2024-03-08 15:21 UTC, b00f commented on config/config.go
> +	conf.Network.DefaultBootstrapAddrStrings = []string{
I think your branch is too old. This is old Testnet.

2024-03-08 17:23 UTC, nagarajmanjunath commented on config/config.go
> -	bootstrapInfosBytes []byte
fixed !

2024-03-08 17:44 UTC, b00f approved these changes

2024-03-08 17:44 UTC, b00f commented on config/errors.go
> +// ConfigError is returned when the store configuration is invalid.
```suggestion
// ConfigError is returned when the node configuration is invalid.
```

2024-03-08 17:44 UTC, b00f commented on txpool/errors.go
> +// ConfigError is returned when the store configuration is invalid.
```suggestion
// ConfigError is returned when the txpool configuration is invalid.
```

2024-03-10 02:01 UTC, b00f commented
@nagarajmanjunath please fix the linting issues

2024-03-10 08:50 UTC, b00f commented
@nagarajmanjunath update the PR description

2024-03-11 13:11 UTC, b00f approved these changes

2024-03-11 13:13 UTC, merged

2024-03-11 13:13 UTC, b00f commented
@nagarajmanjunath Merged with Thanks