fix(grpc): change bytes type to hex string
pactus-project/pactus pull request #1371
Opened 2024-06-26 13:20 UTC by Ja7ad

## Description

Change bytes type in grpc to hex string

## Related issue(s)

- Fixes #377

2024-06-26 14:40 UTC, b00f requested changes

2024-06-26 14:40 UTC, b00f commented on crypto/bls/signature.go
> +func SignatureFromHex(sigHex string) (*Signature, error) {
Please rename it `SignatureFromString`

2024-06-26 14:40 UTC, b00f commented on crypto/bls/signature.go
> +// SignatureFromHex return Signature from hex.
```suggestion
// SignatureFromString decodes the input string and returns the Signature
// if the string is a valid hex encoding of a BLS signature.
```

2024-06-26 14:40 UTC, b00f commented on crypto/bls/signature.go
> +func (sig *Signature) Hex() string {
Remove this function. It is same as `String` method

2024-06-26 14:40 UTC, b00f commented on crypto/hash/hash.go
> +func FromHex(str string) (Hash, error) {
Remove this function. It is same as `FromString`.

2024-06-26 14:40 UTC, b00f commented on crypto/hash/hash.go
> +func (h Hash) Hex() string {
Remove this function. It is same as `String`

2024-06-26 14:40 UTC, b00f commented on types/tx/tx.go
> +func FromHex(str string) (*Tx, error) {
Please rename it to `FromString`

2024-06-26 14:40 UTC, b00f commented on types/tx/tx.go
> +// FromHex return Tx from hex.
// FromString constructs a new transaction from a hex-encoded string.

2024-06-26 14:40 UTC, b00f commented on types/tx/tx.go
> +func (tx *Tx) Hex() (string, error) {
Please rename it to `String` . On error it returns ""

2024-06-26 16:27 UTC, b00f requested changes

2024-06-26 16:27 UTC, b00f commented on crypto/hash/hash_test.go
> +func TestHashFromBytes(t *testing.T) {
Nothing has changed in the implementation, so this test is not necessary.

2024-06-26 16:27 UTC, b00f commented on node/peers.json
> +["/dns/bootstrap4.pactus.org/tcp/21888/p2p/12D3KooWKg6aLa77yAaqMCb45aH5iQuTr5GzRUWUCJ1sZYB5vnoL","/ip4/109.123.253.88/tcp/21888/p2p/12D3KooWFUJhDjYcAXgEnW1pTLRDWnH9CLgBPcezgU7pCpxMngt8","/ip4/194.163
Revert this file and avoid running Pactus on workspace.

2024-06-26 16:30 UTC, b00f commented
@Ja7ad 

In `tx` package you added two methods: `FromHex` and `Hex`

The `Hex` is never used in implementation, `FromHex` is used only once.
Since `tx` is a big object, it make sense that we don't add From/To string to it.

So, remove these function. 
Inside tests you can use: `ts.DecodingHex` for decoding hex easily.

2024-06-26 16:34 UTC, Ja7ad commented
@b00f done

2024-06-27 06:18 UTC, b00f approved these changes

2024-06-27 06:45 UTC, merged