feat: implementation for pip-23
pactus-project/pactus pull request #1397
Opened 2024-07-04 20:14 UTC by ZigBalthazar

#1386

2024-07-04 20:16 UTC, kehiy requested changes
Please run `make proto` and make sure it finishs proprtly.

2024-07-05 06:55 UTC, Ja7ad requested changes
Please write utils service (`utils.proto`) for sign and verify message outside of wallet.

https://github.com/pactus-project/pactus/blob/5727751c38775e35a2a67a324c657289927a0a9a/www/grpc/buf/grpc-gateway.config.yaml#L4

```yaml
    - selector: pactus.Utils.SignMessage
      get: "/pactus/utils/sign_message"

    - selector: pactus.Utils.VerifyMessage
      get: "/pactus/utils/verify_message"
```

https://pips.pactus.org/PIPs/pip-23#specification

2024-07-05 06:55 UTC, Ja7ad commented on util/crypto/crypto.go
> +	if err := pub.Verify([]byte(msg), sig); err != nil {
Function `VerifyMessage` just return true or false, not required to handle error.

2024-07-05 06:55 UTC, Ja7ad commented on util/crypto/crypto_test.go
> +func TestVerifyMessage(t *testing.T) {
Please check invalid signature.

2024-07-05 06:55 UTC, Ja7ad commented on util/crypto/crypto_test.go
> +	sig, err := SignMessageWithPrivateKey(prvStr, msg)
Please check invalid private key

2024-07-05 07:03 UTC, ZigBalthazar commented
> Please write util service for sign and verify message outside of wallet.
> 
> https://pips.pactus.org/PIPs/pip-23#specification

Hi @Ja7ad 
regarding to PIP-23 spec, the `SignMessageWithPrivateKey` and `VerifyMessage` should implement in util and the `SignMessage` should be in wallet service
is it right?

2024-07-05 10:40 UTC, ZigBalthazar commented
Hi @Ja7ad ,
in my opinion we should not put the `sign message` in grpc cause of the sign message need private Key and if we transfer the private key on network could make some security vulnerability

2024-07-05 10:43 UTC, Ja7ad commented
> Hi @Ja7ad ,
> in my opinion we should not put the `sign message` in grpc cause of the sign message need private Key and if we transfer the private key on network could make some security vulnerability 

You should put it, don't have vulnerability.

2024-07-05 11:35 UTC, b00f requested changes

2024-07-05 11:35 UTC, b00f commented on util/crypto/crypto.go
> +func SignMessageWithPrivateKey(prv, msg string) (string, error) {
Please don't define extra util when we have `crypto` package. Use crypto package.
Here we have a wrapped function.

2024-07-05 11:35 UTC, b00f commented on wallet/wallet_test.go
> +	sigStr := "923d67a8624cbb7972b29328e15ec76cc846076ccf00a9e94d991c677846f334ae4ba4551396fbcd6d1cab7593baf3b7"
Rename it to `expectedSig`

2024-07-11 16:10 UTC, Ja7ad requested changes

2024-07-11 16:10 UTC, Ja7ad commented on www/grpc/proto/util.proto
> +service Util {
Please change `Util` to `Utils`

2024-07-11 16:10 UTC, Ja7ad commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Util/Sign_Message_With_PrivateKey"
Change to `Utils`

2024-07-11 16:10 UTC, Ja7ad commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Util/VerifyMessage"
Change to `Utils`

2024-07-11 16:43 UTC, b00f commented on wallet/wallet_test.go
> +	prv, _ := bls.PrivateKeyFromString(
Make sure the error is nil:

```
prv, err := bls.PrivateKeyFromString("...")
require.NoError(t, err)

```

2024-07-11 16:43 UTC, b00f commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Utils/VerifyMessage"
Add new line here

2024-07-11 16:48 UTC, Ja7ad requested changes
@ZigBalthazar please register utils service in json-rpc server.

2024-07-11 16:48 UTC, Ja7ad commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Utils/VerifyMessage"
Please change

```
/pactus/Utils/verify_message
```

2024-07-11 17:01 UTC, b00f requested changes

2024-07-11 17:07 UTC, b00f commented on www/grpc/proto/utils.proto
> +  // The private key to sign message.
Let move private key as first item. Important variables come first.

2024-07-11 17:09 UTC, b00f commented on www/grpc/proto/utils.proto
> +  // The signature of message.
```suggestion
  // The signature of the message.
```

2024-07-11 17:09 UTC, b00f commented on www/grpc/proto/utils.proto
> +  bool is_valid = 1;
// Indicates if the signature is valid (true) or not (false).

2024-07-11 18:29 UTC, Ja7ad requested changes

2024-07-11 18:29 UTC, Ja7ad commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Utils/Verify_Message"
Please don't write capital case in camel case.

```
verify_message
```

2024-07-11 18:29 UTC, Ja7ad commented on www/grpc/buf/grpc-gateway.config.yaml
> +      get: "/pactus/Utils/Sign_Message_With_PrivateKey"
Please don't write capital case in camel case.

```
sign_message_with_privatekey
```

2024-07-11 18:30 UTC, Ja7ad commented
@ZigBalthazar please register utils service in json-rpc server.

https://github.com/pactus-project/pactus/blob/main/www%2Fjsonrpc%2Fserver.go#L57-L60

2024-07-11 19:25 UTC, Ja7ad commented
@ZigBalthazar Please generate proto for new changes.

2024-07-12 06:16 UTC, b00f approved these changes

2024-07-12 06:16 UTC, b00f commented
@ZigBalthazar Thanks

2024-07-12 10:02 UTC, Ja7ad approved these changes

2024-07-12 10:06 UTC, merged