chore(deps): upgrade dependencies
pactus-project/pactus pull request #1501
Opened 2024-09-22 06:47 UTC by Ja7ad

## Description

Upgraded dependencies

2024-09-22 12:40 UTC, kehiy approved these changes
LGTM. based on documents, will be good if you check workflows and socker file dependencies and if they had any updates.

see: #1202

2024-09-23 12:32 UTC, b00f requested changes

2024-09-23 12:32 UTC, b00f commented on .github/workflows/releaser.yml
> -        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Ensure there is always a new line at the end of each file. Please install EditorConfig from https://editorconfig.org/.

2024-09-23 12:32 UTC, b00f commented on www/grpc/gen/docs/json-rpc.md
> +    <td> numeric</td>
Why?

2024-09-23 12:33 UTC, b00f commented on util/testsuite/testsuite.go
> +func (ts *TestSuite) RandAmountRange(minVal, maxVal amount.Amount) amount.Amount {
```suggestion
func (ts *TestSuite) RandAmountRange(minAmt, maxAmt amount.Amount) amount.Amount {
```

2024-09-23 12:34 UTC, b00f commented on util/encoding/encoding_test.go
> +		maxVal   int    // Max size of fixed buffer to induce errors
```suggestion
		maxSize   int    // Max size of fixed buffer to induce errors
```

2024-09-23 12:34 UTC, b00f commented on util/encoding/encoding_test.go
> +		maxVal   int   // Max size of fixed buffer to induce errors
```suggestion
		maxSize   int   // Max size of fixed buffer to induce errors
```

2024-09-23 13:05 UTC, b00f commented on sortition/vrf_test.go
> +		maxSize := uint64(1 * 1e6)
revert this file also

2024-09-23 13:05 UTC, b00f approved these changes

2024-09-23 13:42 UTC, merged