feat(config): add consumption fee configs
pactus-project/pactus pull request #1547
Opened 2024-10-12 19:55 UTC by akbariandev

## Description

In this PR new fee model (consumption fee) configs added.

## Related issue(s)

- Fixes #1541

2024-10-13 16:49 UTC, b00f reviewed
I suggest this text for the example_config.toml

```toml
  # `tx_pool.fee` contains configuration to calulcate the transaction fee.
  [tx_pool.fee]

    # The `fixed_fee` is a constant fee applied to each transaction, regardless of its size or type.
    # Default is `0.01` PAC.
    fixed_fee = 0.01
   
    # The `daily_limit` is the number of bytes an account can send each day without paying a fee.
    # The `daily_limit` is part of he consumptional fee model.
    # To undesrstand how condumptional fee model works, you can refer to 
    # PIP-31: Consumptional Fee Mode: https://pips.pactus.org/PIPs/pip-31
    # Default is `280` bytes.
    daily_limit = 280

    # The `unit_price` defines the fee per byte in PAC.
    # The `unit_price` is part of he consumptional fee model.
    # To undesrstand how condumptional fee model works, you can refer to
    # PIP-31: Consumptional Fee Mode: https://pips.pactus.org/PIPs/pip-31
    # Default is `0.0` PAC.
    unit_price = 0.0
```

2024-10-13 16:49 UTC, b00f commented on config/example_config.toml
> +    fixed_price = 0.01
Please don't change the PIPs name. rename it to `fixed_fee`. 
Please move it to the top.

2024-10-13 16:49 UTC, b00f commented on txpool/config.go
> +	FixedPrice float64 `toml:"fixed_price"`
Please rename it and move to the top.

2024-10-13 16:49 UTC, b00f commented on txpool/config.go
> +		FixedPrice: 0.01,
Same here

2024-10-14 06:18 UTC, Ja7ad requested changes

2024-10-14 06:18 UTC, Ja7ad commented on txpool/config.go
> +	Fee     FeeConfig `toml:"fee"`
@akbariandev Please update to

```go
Fee *FeeConfig `toml:"fee"`
```

2024-10-14 06:18 UTC, Ja7ad commented on txpool/config.go
> +func DefaultFeeConfig() FeeConfig {
@akbariandev Please change `FeeConfig` to `*FeeConfig`

2024-10-14 06:18 UTC, Ja7ad commented on txpool/config.go
> +	return FeeConfig{
@akbariandev Please change to `return *FeeConfig{}`

2024-10-14 08:18 UTC, b00f commented on txpool/config.go
> +		FixedFee:   0.01,
Same here

2024-10-14 08:19 UTC, b00f commented on config/example_config.toml
> +    # PIP-31: Consumptional Fee Mode: https://pips.pactus.org/PIPs/pip-31
```suggestion
    # PIP-31: Consumptional Fee Mode (https://pips.pactus.org/PIPs/pip-31)
```

2024-10-14 08:20 UTC, b00f commented on config/example_config.toml
> +    # PIP-31: Consumptional Fee Mode: https://pips.pactus.org/PIPs/pip-31
```suggestion
    # PIP-31: Consumptional Fee Mode (https://pips.pactus.org/PIPs/pip-31)
```

2024-10-14 09:37 UTC, Ja7ad approved these changes

2024-10-14 12:24 UTC, b00f approved these changes

2024-10-14 12:24 UTC, merged