feat(wallet): add wallet service API
pactus-project/pactus pull request #1548
Opened 2024-10-13 08:10 UTC by Ja7ad

## Description

- [x]  Get Total Stake - Get the total stake of the wallet
- [x] Get Address Info - Get the address info for the given address
- [x] Set Label - Set label for the given address
- [ ] Get Wallet Info - Return the information about wallet
- [ ] List Wallets - Return the list of wallets inside wallet directory
- [ ] List Address - Return the list of addresses in wallet, it accepts 

## Related issue(s)

- Resolves #1210 #1342

2024-10-13 08:11 UTC, Ja7ad commented
@b00f Can write more details what is it response of:

- Get Wallet Info
- List Wallets
- List Address

2024-10-14 11:48 UTC, b00f commented
> Get Wallet Info

Information about wallet, like Wallet name, version, Is Encrypted, Creation time, etc

> List Wallets

For listing wallets, we can list files inside the `wallets` directory. The better solution is to keep the list of wallets in `wallets.json`. 

> List Address

The list of all addresses in a wallet.

2024-10-16 07:03 UTC, b00f requested changes

2024-10-16 07:03 UTC, b00f commented on wallet/manager.go
> +		return nil, status.Errorf(codes.NotFound, "wallet is not loaded")
One potential refactor is to define proper error types here.

2024-10-16 07:03 UTC, b00f commented on wallet/manager.go
> +	return append(wlt.AllValidatorAddresses(), wlt.AllAccountAddresses()...), nil
Use `wlt.AddressInfos()`

2024-10-16 07:03 UTC, b00f commented on wallet/wallet.go
> +	Crc        uint32
Do we really need to return Crc? I don't see any reason for that

2024-10-16 10:13 UTC, b00f commented on wallet/manager.go
> +		return nil, status.Errorf(codes.NotFound, "wallet is not loaded")
We should define error types here.

2024-10-16 10:13 UTC, merged