feat(init): create one ed25519 reward address for all validators
pactus-project/pactus pull request #1570
Opened 2024-10-28 09:17 UTC by akbariandev

## Description
In these changes, we create 1 reward address (ed25519) instead 7-32 addresses for all validators when initializing a node.

## Related issue(s)

If this Pull Request is related to an issue, mention it here.
- Fixes #1555

2024-10-28 09:22 UTC, Ja7ad reviewed
@akbariandev Please test it on testnet and localnet.

2024-10-29 05:25 UTC, Ja7ad commented
> > **Is it backward compatible?**
> > Let's say you have a validator without an Ed address. After this change, the node won't start because it looks for an Ed reward address, which does not exist.
> 
> Fixed in the last commit and tested in localnet with both bls and ed25529 reward addresses. Please review for merge

Can you check functionality create new validator in GUI and pactus-wallet, When create new validator auto created a bls reward address.

2024-10-29 06:31 UTC, b00f requested changes

2024-10-29 06:31 UTC, b00f commented on cmd/cmd.go
> +		"Reward address ", "")
Extra space here:

```suggestion
		"Reward address", "")
```

2024-10-29 06:31 UTC, b00f commented on cmd/cmd.go
> +	rewardAddrs := addressInfo.Address
Rename it to `rewardAddr` without `s`

2024-10-29 15:03 UTC, akbariandev commented
All validators get the single new ED25519 address. Also new validator added and after running node, that new validator gets exact single address. The flow tested in cli nad GUI. Transfer and bond works fine only rewarding process may need to test more and because of low staking on my test net nodes the reward process testing may get long time.


![image](https://github.com/user-attachments/assets/25ec32bc-5b66-483d-9647-40634a9b21da)

2024-10-29 18:53 UTC, b00f commented on cmd/cmd.go
> +// It returns an error if the genesis doc or default_wallet can't be found inside the working directory.1234
please remove `1234 `

2024-10-29 18:54 UTC, b00f requested changes

2024-10-29 18:54 UTC, b00f commented on cmd/gtk/startup_assistant.go
>  			nodeInfo += "\nReward addresses:\n"
```suggestion
			nodeInfo += "\nReward address:\n"
```

2024-10-29 18:54 UTC, b00f commented on cmd/daemon/init.go
>  		cmd.PrintInfoMsgBoldf("Reward addresses:")
```suggestion
		cmd.PrintInfoMsgBoldf("Reward address:")
```

2024-10-31 18:01 UTC, Ja7ad approved these changes

2024-11-01 11:15 UTC, b00f approved these changes

2024-11-01 11:16 UTC, merged