refactor: rename send to transfer.
pactus-project/pactus pull request #469
Opened 2023-05-11 10:13 UTC by yenkhoon

## Description
Rename send to transfer.

2023-05-11 10:34 UTC, b00f requested changes
rename `NewSendTx` to `NewTransferTx`

2023-05-11 10:34 UTC, b00f commented on cmd/wallet/main.go
> +		k.Command("send", "Create, sign and publish a send transaction", TransferTx())
```suggestion
		k.Command("transfer", "Create, sign and publish a Transfer transaction", TransferTx())
```

2023-05-11 10:34 UTC, b00f commented on cmd/wallet/main.go
> +		k.Command("send", "Create, sign and publish a send transaction", TransferTx())
```suggestion
		k.Command("transfer", "Create, sign and publish a Transfer transaction", TransferTx())
```

2023-05-11 10:34 UTC, b00f commented on cmd/wallet/main.go
>  		k.Command("bond", "Create, sign and publish a bond transaction", BondTx())
```suggestion
		k.Command("bond", "Create, sign and publish a Bond transaction", BondTx())
```

2023-05-11 10:34 UTC, b00f commented on cmd/wallet/main.go
>  		k.Command("unbond", "Create, sign and publish an unbond transaction", UnbondTx())
```suggestion
		k.Command("unbond", "Create, sign and publish an Unbond transaction", UnbondTx())
```

2023-05-11 10:34 UTC, b00f commented on cmd/wallet/main.go
>  		k.Command("withdraw", "Create, sign and publish a withdraw transaction", WithdrawTx())
```suggestion
		k.Command("withdraw", "Create, sign and publish a Withdraw transaction", WithdrawTx())
```

2023-05-12 04:38 UTC, b00f commented on types/tx/payload/payload.go
>  		return "send"
```suggestion
		return "transfer"
```

2023-05-12 04:38 UTC, b00f commented on types/tx/payload/payload.go
>  		return "send"
```suggestion
		return "transfer"
```

2023-05-17 16:36 UTC, b00f commented
@yenkhoon You forgot to rename  `NewSendTx` to `NewTransferTx`

2023-05-17 17:17 UTC, yenkhoon commented
> 

Okie i will change it

2023-05-19 19:11 UTC, b00f approved these changes

2023-05-19 19:11 UTC, b00f commented
@yenkhoon Thanks

2023-05-19 19:11 UTC, merged