feat: Add CalcualteFee in GRPC
pactus-project/pactus pull request #601
Opened 2023-07-26 17:47 UTC by ZigBalthazar

## Description

* add `calculateFee` to GRPC
* change wallet `setFee `and `calcFee`
* change some typo

## Related issue(s)

- Fixes #590

2023-07-27 11:19 UTC, b00f approved these changes

2023-07-27 11:19 UTC, b00f commented on node/node.go
> +	logger.Info("You are running a pactus block chain",
Please revert this change.

2023-07-27 11:19 UTC, b00f commented on state/facade.go
> +	CalcFee(amount int64, payloadType payload.Type) (int64, error)
To be consistent with other part of the project, rename it to `CalculateFee`

2023-07-27 11:19 UTC, b00f commented on state/mock.go
> +	return 0, nil
Let's return random number. Like: `ts.RandInt64(1^e9)`
Maybe some test fails, (Unbond Tests?). Then check type here.

2023-07-27 11:19 UTC, b00f commented on state/state_test.go
> +		fee, err := td.state2.CalcFee(int64(test.amount), payload.PayloadTypeTransfer)
```suggestion
		fee, err := td.state2.CalcFee(test.amount, payload.PayloadTypeTransfer)
```

This fix the linting issue

2023-07-27 11:19 UTC, b00f commented on state/state_test.go
> +		assert.Equal(t, int64(test.expectedFee), fee)
```suggestion
		assert.Equal(t, test.expectedFee, fee)
```

Same.

2023-07-27 11:19 UTC, b00f commented on wallet/client_test.go
> +func (s *transactionServer) GetFee(_ context.Context,
This function is not necessary here.

2023-07-27 11:19 UTC, b00f commented on wallet/client.go
> +	res, err := c.transactionClient.CalculateFee(context.Background(), &pactus.CalculateFeeRequest{Amount: amount, PayloadType: pactus.PayloadType(payloadType)})
```suggestion
	res, err := c.transactionClient.CalculateFee(context.Background(), &pactus.CalculateFeeRequest{
	Amount: amount, PayloadType: pactus.PayloadType(payloadType)})
```

Break this long line

2023-07-27 11:23 UTC, b00f commented
@ZigBalthazar 

Thanks for this PR. It fix the `CalculateFee` related issues.

Still, some items need to be fixed:
1- Please update [grpc-gateway.config.yaml](https://github.com/pactus-project/pactus/blob/main/www/grpc/grpc-gateway.config.yaml)
2- Make sure the linting check passes: `make check`
3- Fix the GUI issues.

2023-07-30 06:43 UTC, ZigBalthazar commented
@b00f

2023-07-30 06:57 UTC, b00f requested changes

2023-07-30 06:57 UTC, b00f commented on cmd/gtk/utils.go
> +		fee, err := w.CalculateFee(amount, payload.PayloadTypeTransfer)
This only works for Transfer type.
To ensure the system works fine with Non-transfer payloads, it's better to pass the payload type as an argument to this function.

2023-07-30 06:57 UTC, b00f commented on node/node.go
> +	logger.Info("You are running a pactus blockchain",
```suggestion
	logger.Info("You are running a Pactus blockchain",
```

2023-07-30 06:57 UTC, b00f commented on state/state_test.go
> +		fee, err := td.state2.CalculateFee(test.amount, payload.PayloadTypeTransfer)
Let's make this test better. Change tests structure to:
```
tests := []struct {
		amount          int64
		pldType         payload.Type
		fee             int64
		expectedFee     int64
		expectedErrCode int
	}
	```
	
	You can add more tests for non-transfer types

2023-07-30 06:57 UTC, b00f commented
@ZigBalthazar 
Thanks. Everything looks good to me. Just 2 small changes.

2023-07-30 08:06 UTC, kehiy commented on cmd/gtk/dialog_transaction_bond.go
> +		updateFeeHint(amountHint, amtStr, wallet, payload.PayloadTypeBond)
```suggestion
		updateFeeHint(amountHint, amtStr, wallet,  payload.PayloadTypeBond)
```

2023-07-30 08:34 UTC, b00f approved these changes

2023-07-30 08:35 UTC, merged