feat: peer Sent and Received Bytes metrics
pactus-project/pactus pull request #618
Opened 2023-07-31 15:49 UTC by ZigBalthazar

## Description

Regarding issue #605, I have made some updates. I have added "SentBytes" and "ReceivedBytes" to "peer" and made changes to the "IncreaseReceivedBytesCounter" and "IncreaseSentBytesCounter" functions. Additionally, I have modified the "sendTo" and "broadcast" functions and updated the Protos.

 ## Related issue(s)

- Fixes #605

2023-07-31 16:01 UTC, ZigBalthazar commented
I made a mistake while managing my local git branches, and this resulted in 31 commits. 🥲

2023-08-01 09:02 UTC, b00f requested changes

2023-08-01 09:02 UTC, b00f commented on sync/sync.go
> +		// pid := sync.SelfID()
Please remove this commented line

2023-08-01 10:16 UTC, ZigBalthazar commented
Hi @b00f 

Could you kindly provide me with your feedback?

2023-08-01 12:42 UTC, b00f approved these changes

2023-08-01 12:44 UTC, merged