feat: Notifee service events
pactus-project/pactus pull request #628
Opened 2023-08-10 16:15 UTC by ZigBalthazar

@b00f 

## Description

Regarding issue #622  , I made some updates to the peerSet struct which now includes `ConnectedPeers`. Additionally, I added `EventTypeConnect` and `EventTypeDisconnect` to the events. To handle the `ConnectedPeers`, 
I added two functions in `peer_set.go`:
 `AddNewconnectedPeer` and `DisconnectedPeer`.

## Related issue(s)

- Fixes #622

2023-08-10 16:57 UTC, b00f requested changes

2023-08-10 16:57 UTC, b00f commented on network/notifee.go
> +	// TODO: Log
Add log here please. It is very useful in future.
Pass logger to NotifeeService

2023-08-10 16:57 UTC, b00f commented on network/notifee.go
> +	// Handle listen close event if needed.
Same here

2023-08-10 16:57 UTC, b00f commented on network/interface.go
> +type ConnectEvent struct {
Let's add a comment here
```
// ConnectEvent represents a peer connection event.
```

2023-08-10 16:57 UTC, b00f commented on network/interface.go
> +		return "connect-msg"
```suggestion
		return "connect"
```

2023-08-10 16:57 UTC, b00f commented on network/interface.go
> +		return "disconnect-msg"
```suggestion
		return "disconnect"
```

2023-08-10 16:57 UTC, b00f commented on network/interface.go
> +		return "connect-msg"
It is not a message actually.

2023-08-11 09:15 UTC, themantre approved these changes

2023-08-11 09:43 UTC, themantre approved these changes

2023-08-11 10:11 UTC, b00f approved these changes

2023-08-11 10:12 UTC, merged