refactor(sync): refactoring syncing process
pactus-project/pactus pull request #676
Opened 2023-09-05 16:47 UTC by b00f

## Description

This PR includes these changes:

1- `HeartBeat` message is removed.
2- `HelloAck` message is added. Once a node receives a `HelloAck`, it can start sending messages.
3- `MaxOpenSessions` is removed and the maximum number of sessions should be the same as the number of connected peers.
4- Syncing process is based on time, not height. If the last block time is more than 20 seconds behind the current time, the node starts syncing.

2023-09-05 17:31 UTC, kehiy approved these changes
LGTM.
That's exactly what we discussed!

2023-09-06 07:18 UTC, amirvalhalla commented on sync/bundle/message/hello.go
> +	BlockHash   hash.Hash         `cbor:"10,keyasint"`
`cbor:"9"` has missed, please fix that.

2023-09-06 07:29 UTC, amirvalhalla requested changes
@b00f 
please resolve request changes.

2023-09-06 14:08 UTC, amirvalhalla approved these changes

2023-09-06 15:01 UTC, b00f commented
@amirvalhalla could you please double check it. If anything missed, mention me.

2023-09-07 05:59 UTC, amirvalhalla commented on sync/bundle/message/hello.go
> +	BlockHash   hash.Hash         `cbor:"10,keyasint"`
@b00f 
cbor:"9" has missed, please fix it.

2023-09-07 05:59 UTC, amirvalhalla requested changes
@b00f 
please resolve request changes.

2023-09-07 11:28 UTC, themantre commented on sync/bundle/message/hello.go
> +	BlockHash   hash.Hash         `cbor:"9,keyasint"`
@amirvalhalla it is fixed here. Please check again.

2023-09-07 11:44 UTC, b00f commented on sync/bundle/message/hello.go
> +	BlockHash   hash.Hash         `cbor:"9,keyasint"`
@amirvalhalla please check here

2023-09-07 14:40 UTC, merged