Feat pip 2 and 3
pactus-project/pactus pull request #699
Opened 2023-09-14 18:28 UTC by amirvalhalla

## Description

implementing pip2 and pip3

## Related issue(s)

If this Pull Request is related to an issue, mention it here.
- Fixes #695

2023-09-14 18:30 UTC, amirvalhalla commented
@b00f 
still some unit tests fail. I didn't fix them because I've wanted you see them, maybe I make mistake in business logic.

2023-09-16 14:54 UTC, b00f requested changes

2023-09-16 14:54 UTC, b00f commented on cmd/wallet/tx.go
> +		"transaction lock-time, if not specified will be current height")
```suggestion
		"transaction lock-time, if not specified will be the current height")
```

2023-09-16 14:54 UTC, b00f commented on execution/execution.go
> +		fmt.Printf("trx.LockTime() %d , sb.CurrentHeight() %d, interval: %d\n", trx.LockTime(), sb.CurrentHeight(), interval)
Please remove this log

2023-09-16 14:54 UTC, b00f commented on sandbox/sandbox.go
> +
remove this line also

2023-09-16 14:54 UTC, b00f commented on sandbox/sandbox.go
> +	if sb.committedTrxs[txID] != nil {
Can you add test for this? It can include `CommitTransaction` as well in same test.
Scenario, Commit a transaction, and this should return false

2023-09-16 14:54 UTC, b00f commented on sandbox/sandbox.go
> +	if sb.committedTrxs[txID] != nil {
You may also check:  `AccumulatedFee`

2023-09-16 14:54 UTC, b00f commented on txpool/pool_test.go
> -	transferTx := tx.NewTransferTx(block1000000.Stamp(), acc1.Sequence()+1, acc1Signer.Address(),
To make the test better, let's define `randHeight` and `randBlock`, then `lockTime` can be `randHeight+1` etc.

2023-09-16 14:54 UTC, b00f commented on types/account/account_test.go
>  func TestIncSequence(t *testing.T) {
I think we can remove this test

2023-09-16 16:30 UTC, b00f commented
@amirvalhalla Thanks

2023-09-16 16:31 UTC, b00f approved these changes

2023-09-16 16:31 UTC, merged