chore(lint): enable nonamedreturns linter
pactus-project/pactus pull request #707
Opened 2023-09-23 14:33 UTC by allnil

enable nonamedreturns linter
fix code which was highlighted by nonamedreturns

https://github.com/pactus-project/pactus/issues/644

2023-09-23 16:02 UTC, kehiy approved these changes
@allnil Thanks.
LGTM.

@b00f Can you have a final review and merge?

2023-09-24 14:22 UTC, amirvalhalla approved these changes

2023-09-24 14:25 UTC, amirvalhalla commented
@allnil 
thanks.
right now, we have 2 PIPs (`PIP-8`,`PIP-9`) that we've implemented them/we're implementing them so you're changes will make conflict with existing PRs etc...
maybe merging your PR takes a bit more time but we will merge it as soon as possible.

2023-09-25 11:43 UTC, b00f requested changes

2023-09-25 11:43 UTC, b00f commented on sortition/vrf.go
>  // Evaluate returns a random number between 0 and max with the proof.
```suggestion
// Evaluate returns a provable random number between [0, max) along with a proof.
// It returns the random number and the proof that can regenerate the random number using
// the public key of the signer, without revealing the private key.
```

2023-09-25 11:43 UTC, b00f commented on sortition/vrf.go
>  // Verify ensures the proof is valid.
```suggestion
// Verify checks if the provided proof, based on the seed and public key, is valid.
// If the proof is valid, it calculates the random number that
// can be generated based on the given proof.
```

2023-09-26 04:56 UTC, b00f approved these changes

2023-09-26 07:44 UTC, b00f approved these changes

2023-09-26 07:45 UTC, merged

2023-09-26 07:46 UTC, b00f commented
@allnil Thank you. We hope to see you more on Pactus. 
Join us on [Discord](https://discord.gg/H5vZkNnXCu), where we discuss core development further.