feat: implementing pip-8
pactus-project/pactus pull request #711
Opened 2023-09-26 17:09 UTC by amirvalhalla

## Description

This PR implemented [pip-8](https://pips.pactus.org/PIPs/pip-8)

It also fixes #510

2023-09-26 17:22 UTC, kehiy approved these changes

2023-09-26 18:10 UTC, b00f requested changes
@amirvalhalla 

Thanks. An important and crucial PR.

2023-09-26 18:10 UTC, b00f commented on sync/handler_hello_test.go
> +			msg.Sign([]*bls.ValidatorKey{valKey})
This function doesn't perform any actions. It can be removed.
A better approach is to check the type of the error.

2023-09-26 18:10 UTC, b00f commented on sync/handler_hello_test.go
> +			msg.Sign([]*bls.ValidatorKey{valKey})
same here

2023-09-26 18:10 UTC, b00f commented on sync/handler_hello_test.go
> +			msg.Sign([]*bls.ValidatorKey{valKey})
and here

2023-09-26 18:10 UTC, b00f commented on sync/sync.go
> +		// TODO: cache address for the better performance
This comment can be removed. We cache the address inside the `ValidatorKey` object.

2023-09-26 18:10 UTC, b00f commented on types/proposal/proposal_test.go
> +
Here also, (extra line)

2023-09-26 18:10 UTC, b00f commented on wallet/addresspath/path.go
> +// m/12381'/21888'/1' -> public key
remove these comments

2023-09-26 20:31 UTC, amirvalhalla commented on store/interface.go
> -				Address: trx.Payload().Signer(),
@b00f 
I didn't change, based on git blames @kehiy changed this section.
what should we do now?

2023-09-27 16:45 UTC, b00f approved these changes

2023-09-27 19:01 UTC, merged