feat: create new validator address (CLI and GUI)
pactus-project/pactus pull request #757
Opened 2023-10-20 01:37 UTC by jemiluv8

## Description
Add ability to Create Validator Address in CLI and GUI Applications

## Related issue(s)
- Fixes #713
/claim #713

## GUI SCREENSHOT
<img width="802" alt="Screenshot 2023-10-20 at 1 36 32 AM" src="https://github.com/pactus-project/pactus/assets/119384208/5b234264-24d9-443c-9e31-f8f9f8071535">

### CLI SCREENSHOT - DEBUGGING AND TESTING
<img width="624" alt="Screenshot 2023-10-20 at 2 08 14 AM" src="https://github.com/pactus-project/pactus/assets/119384208/525162f4-db72-4cc5-9dd4-b740b01912dd">

2023-10-20 01:44 UTC, jemiluv8 reviewed
@b00f, I just completed a self-review.
This PR is ready for review and any requests for changes.

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/assets/ui/widget_wallet.ui
> +                  <object class="GtkToolButton" id="id_button_new_validator_address">
New button to "Add New Validator Address"

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/model_wallet.go
> +func (model *walletModel) createAddress(accountType wallet.AddressType) error {
Modified original createAddress to now take an argument.

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/widget_wallet.go
> +	getToolButtonObj(builder, "id_button_new_validator_address").SetIconWidget(AddIcon())
using same AddIcon here

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/widget_wallet.go
> +		"on_new_validator_address": w.onNewValidatorAddress,
Introduce new singnal(on_new_validator_address) for creating new validator address

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/widget_wallet.go
> +	err := ww.model.createAddress(wallet.AddressTypeBLSAccount)
Updated this to specify address type

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/gtk/widget_wallet.go
> +func (ww *widgetWallet) onNewValidatorAddress() {
Call back for 'on_new_validator_address' signal. Creates a validator address.

2023-10-20 01:44 UTC, jemiluv8 commented on cmd/wallet/address.go
> +		isForBLSAccount := *addressType == w.AddressTypeBLSAccount.String()
Cli related changes to support specifying command to create validator address

2023-10-20 01:44 UTC, jemiluv8 commented on wallet/client.go
> +type AddressType string
Introduced AddressType to be used in other places so we don't use the strings directly.

2023-10-20 06:37 UTC, themantre commented
It's better to add a new dialog for creating new address, like:
```
+----------------------------------------------------------------+
| New address dialog                                             |
+----------------------------------------------------------------+
|                                                                |
| Label: [                               ]                       |
| Type:  [   \ Account               \/  ]                       |
|            \ Validator                                         |
|                                                                |
|                                              [Close] [ OK]     |
+----------------------------------------------------------------+
```

2023-10-20 07:03 UTC, themantre requested changes

2023-10-20 07:03 UTC, themantre commented on cmd/wallet/address.go
> +		if !isForBLSAccount || !isForValidatorAccount {
It is complex. You can make it simple like:

if addrType == "fo" { ... }
else if addrType = "bar" { .. }
else { error }

Feel free to use switch/case

2023-10-20 08:04 UTC, jemiluv8 commented
ok @themantre, I'm working on the changes.

2023-10-20 16:53 UTC, themantre commented
Good job @jemiluv8 . There are some small linting issues.
Please give me time, I will review the code tomorrow.

2023-10-20 17:23 UTC, jemiluv8 commented
@themantre  I will fix the lint issues. I'm having challenge "refreshing" the
list of addresses after creating a new address from the modal.

Newly created addresses do not show in the addresses table until I switch views
and come back. I'd appreciate any pointers in that regard. 
I'm looking into it in the meantime.

2023-10-21 01:03 UTC, jemiluv8 commented
Fixed issues with newly created address not appearing in the list of addresses.
Also attempted a fix for lint issues. Its ready for review.

2023-10-22 12:04 UTC, themantre commented
@jemiluv8 
Please check https://github.com/jemiluv8/pactus/pull/1

2023-10-24 23:53 UTC, b00f approved these changes

2023-10-24 23:53 UTC, merged

2023-10-24 23:53 UTC, b00f commented
@jemiluv8 Thanks