chore: updating linters
pactus-project/pactus pull request #772
Opened 2023-10-23 17:11 UTC by b00f

## Description

This PR updates the linters and fix some linting issues.

2023-10-23 17:15 UTC, b00f commented
Please don't merge it. We may still update version 0.15.1.

2023-10-23 19:14 UTC, kehiy requested changes
@b00f Everything looks good, but one additional thing you can do here.
in lint.yml workflow instead of installing golangci lint and running make check, just use golangci lint github action to do this.

2023-10-28 18:57 UTC, themantre approved these changes

2023-10-28 18:58 UTC, themantre approved these changes

2023-10-28 18:58 UTC, merged