feat(grpc): endpoints for creating raw transaction
pactus-project/pactus pull request #832
Opened 2023-12-01 20:54 UTC by kehiy

## Related issue(s)

- Fixes #351

2023-12-02 13:41 UTC, kehiy commented
@b00f can you have a review?

2023-12-05 18:35 UTC, b00f requested changes

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction_test.go
> +		tx, privateKey := ts.GenerateTestTransferTx()
To prevent import shadowing, rename `tx` to `trx`

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction.go
> +		return &pactus.GetRawTransactionResponse{}, err
Why not `nil, err`?

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction.go
> +		return &pactus.GetRawTransactionResponse{}, err
Why not `nil, err`?

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction_test.go
> +		valAddr := ts.RandValAddress()
To be compatible with the rest of the test: use: `tx, privateKey := ts.GenerateTestUnbondTx()`

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction_test.go
> +			Sender:    privateKey.PublicKeyNative().AccountAddress().String(),
You can use `trx.Signer.Address()`

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction_test.go
> +			ValidatorAddress: valAddr.String(),
You can use `trx.Signer.Address()`

2023-12-05 18:35 UTC, b00f commented on www/grpc/transaction.go
> +		return &pactus.GetRawTransactionResponse{}, err
Same here: `nil, err`

2023-12-05 18:36 UTC, b00f commented
@kehiy Everything looks good, Just small issues.

2023-12-05 18:53 UTC, closed without merging