chore(daemon): removing password, entropy and validator number as prompt, and adding flags instead
pactus-project/pactus pull request #943
Opened 2024-01-17 07:34 UTC by kehiy

## Description

In this PR I removed the validator number, password, and entropy as prompt and hard-coded values. now we get them as flags from the user, this helps other interfaces and clients like GUI use this `init` command with ease.

2024-01-17 08:48 UTC, b00f requested changes

2024-01-17 08:48 UTC, b00f commented on cmd/daemon/init.go
> +		if *valNumOpt < 1 || *valNumOpt > 32 {
We can't change the previous behavior.
I suggest:
1- Don't set default in flags
2- If it is not set (or zero) ask user to set it manually

2024-01-17 15:35 UTC, b00f commented on cmd/daemon/init.go
> -		cmd.PrintLine()
Still we break the previous behaviour. If user didn't set the number of validator, it should work as before.

2024-01-17 15:35 UTC, b00f commented on cmd/daemon/init.go
> -		numValidators := cmd.PromptInputWithRange("Number of Validators", 7, 1, 32)
Still we break the previous behaviour. If user didn't set the number of validator, it should work as before.

2024-01-17 15:39 UTC, b00f commented on cmd/daemon/init.go
> -		numValidators := cmd.PromptInputWithRange("Number of Validators", 7, 1, 32)
It should be like:
```
var valNum int
if *valNumOpt == 0 {
// .... old code
} else {
// ... new code
}
```

2024-01-17 15:44 UTC, kehiy commented
@b00f fixed.

2024-01-18 07:34 UTC, b00f approved these changes

2024-01-18 07:34 UTC, merged